# Generated by Django 3.2.20 on 2023-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click The Link Above To Read Blogpost', max_length=220),
        ),
    ]
