# Generated by Django 3.2.20 on 2023-09-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
